version: "3"
services:
  # Single DB instance - Single DB schema per service
  postgres:
    container_name: "postgres"
    image: postgres:10.9
    restart: always
    environment:
      POSTGRES_USER: "rmhub"
      POSTGRES_PASSWORD: "123456"
    volumes:
      - /rmhub/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
